Aniket_Assignment_8
KrishnaKTechnocredits/JAVATechnoJuly2021 pull request #303
Opened 2021-08-11 04:07 UTC by aniket0811

![image](https://user-images.githubusercontent.com/83530588/128968204-8b731e9f-f746-435f-ad25-548a87516618.png)

2021-08-11 15:56 UTC, VaibhavTati requested changes
Update the code as per the given problem statement, and add method to set user details.

2021-08-11 15:56 UTC, VaibhavTati commented on src/aniket/Assignment_8.java
> +	static int AllprintBalanceCount;
Variable names should be in Camel casing 
i.e **AlldebitCnt** should be written as **allDebitCnt**

2021-08-11 15:56 UTC, VaibhavTati commented on src/aniket/Assignment_8.java
> +public class Assignment_8 {
Class name should be appropriate and self explanatory with respect to the code i.e. it can be **BankingSystem**

2021-08-11 15:56 UTC, VaibhavTati commented on src/aniket/Assignment_8.java
> +
You should have **setUserDetails** method to set **username** and **initial Balance** 
Update the code as the the given problem statement.

2021-08-12 15:16 UTC, aniket0811 reviewed
Corrected the changes as per comment.

2021-08-13 06:14 UTC, VaibhavTati commented
Hello Aniket,

The code is not as per the given requirement.
In the Problem statement it is mentioned that, **You should have setUserDetails method to set username and initial Balance** 

Please update the code accordingly.

You can refer below PR for your reference
**Reference PR :** https://github.com/KrishnaKTechnocredits/JAVATechnoJuly2021/pull/295/files

2021-08-14 12:29 UTC, KrishnaKTechnocredits approved these changes
Code looks good to me!
Keep doing well!

2021-08-14 12:31 UTC, merged