Varun_Assignment_9
KrishnaKTechnocredits/JAVATechnoJuly2021 pull request #365
Opened 2021-08-11 14:54 UTC by varunj822

![image](https://user-images.githubusercontent.com/88383033/129052328-a7657676-bedf-4a86-90c4-815175bb1f4c.png)

2021-08-11 16:24 UTC, harshvegada commented on src/varun/Assignment_9.java
> +			maggieStock = maggieStock-itemQuantity;
Here first you should check whether we have enough stock that fulfilled the current requirement of customer?

2021-08-11 16:25 UTC, harshvegada commented on src/varun/Assignment_9.java
> +			System.out.println(itemName+ " is running out of stock with only " +maggieStock+ " quantity remaining");
why are saying if stock is less than 10 then stock is not available ?

2021-08-11 16:37 UTC, harshvegada requested changes
Check requirement again and update this

Reference 
https://github.com/KrishnaKTechnocredits/JAVATechnoJuly2021/pull/377/files

2021-08-12 05:52 UTC, harshvegada commented on src/varun/Assignment_9.java
> +			System.out.println(itemName+ " is running out of stock with only " +maggieStock+ " quantity remaining");
Yes, similar to OOS
OK

2021-08-12 08:36 UTC, varunj822 commented
![image](https://user-images.githubusercontent.com/88383033/129165737-048160bc-b5dc-437e-8b98-f212fa2d0949.png)

2021-08-13 17:24 UTC, harshvegada approved these changes
Code looks good to me,
 Good to merge!

2021-08-13 17:24 UTC, merged