Purshottam_Assignment9
KrishnaKTechnocredits/JAVATechnoJuly2021 pull request #372
Opened 2021-08-11 15:48 UTC by purshottam94

![image](https://user-images.githubusercontent.com/71837062/129061246-f7d1b6ff-e207-4212-b9b7-dfa2b9ff44e2.png)

2021-08-11 16:12 UTC, surabhi-9 requested changes
Rewrite the code again with proper validation like :
1. if packets are less than 0, show insufficient error
2. if requested packets are less than available packets then deduct requested quantity from finalQuantity else show message that we can give you packets (packets-totalQuantity )
and assign total packets to 0.

2021-08-11 16:49 UTC, purshottam94 commented
> Rewrite the code again with proper validation like :
> 
> 1. if packets are less than 0, show insufficient error
> 2. if requested packets are less than available packets then deduct requested quantity from finalQuantity else show message that we can give you packets (packets-totalQuantity )
>    and assign total packets to 0.

I have given validation inside displayOutofStockProduct and called this method inside purchaseProcess

2021-08-11 17:04 UTC, surabhi-9 commented on src/purshottamJoshi/Shop.java
> +		if(maggie >  totalMaggieStock) {
available packets will be when totalMaggieStock > maggie . so this condition is wrong

2021-08-11 17:56 UTC, purshottam94 reviewed
updated Purshottam_Assignment9 pr 
![image](https://user-images.githubusercontent.com/71837062/129079006-e476ffbc-7493-49ae-8290-f78b66e1eb95.png)
@surabhi-9 @harshvegada @KrishnaKTechnocredits

2021-08-11 17:57 UTC, purshottam94 commented on src/purshottamJoshi/Shop.java
> +		if(maggie >  totalMaggieStock) {
> available packets will be when totalMaggieStock > maggie . so this condition is wrong

Updated same.

2021-08-11 18:10 UTC, surabhi-9 approved these changes
code looks good to me

2021-08-14 12:43 UTC, KrishnaKTechnocredits approved these changes
Code looks good to me!
Keep doing well!

2021-08-14 12:54 UTC, merged