Rasika_Assignment_10
KrishnaKTechnocredits/JAVATechnoJuly2021 pull request #422
Opened 2021-08-12 04:24 UTC by RasikaNitin

![image](https://user-images.githubusercontent.com/88392949/129138025-3280936f-1409-4073-bee7-0fc39876ba26.png)

2021-08-12 05:14 UTC, surabhi-9 commented on src/rasika/Assignment10.java
> +			if(number % 2 == 0) {
Validation is wrong. have to use like number % index = = 0 then booleanFlag=false, then break

2021-08-12 05:15 UTC, surabhi-9 commented on src/rasika/Assignment10.java
> +		boolean status = true;
try to use meaningfull variable name like isPrimeNumber .

2021-08-12 05:15 UTC, surabhi-9 requested changes
Please rewrite the validation for prime number again with correct logic

2021-08-14 13:01 UTC, KrishnaKTechnocredits approved these changes
Code looks good to me!
Keep doing well!

2021-08-14 13:02 UTC, merged